version: '3.0'
services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: punk
    ports:
      - "5432:5432"
    volumes:
      - ./database-config/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: none

