CREATE TABLE malt
(
    id   INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE hop
(
    id   INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE yeast
(
    id   INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE beer
(
    id                 INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name               TEXT NOT NULL,
    tagline            TEXT,
    first_brewed       DATE,
    description        TEXT,
    image_url          TEXT,
    abv                DECIMAL,
    ibu                DECIMAL,
    target_fg          DECIMAL,
    target_og          DECIMAL,
    ebc                DECIMAL,
    srm                DECIMAL,
    ph                 DECIMAL,
    attenuation_level  DECIMAL,
    volume_value       DECIMAL,
    volume_unit        TEXT,
    boil_volume_value  DECIMAL,
    boil_volume_unit   TEXT,
    mash_temp_value    DECIMAL,
    mash_temp_unit     TEXT,
    mash_temp_duration INTEGER,
    fermentation_value DECIMAL,
    fermentation_unit  TEXT,
    twist              TEXT,
    yeast_id           INTEGER,
    brewers_tips       TEXT,
    contributed_by     TEXT,
    CONSTRAINT fk_yeast FOREIGN KEY (yeast_id) REFERENCES yeast (id)
);

CREATE TABLE beer_malt
(
    beer_id      INTEGER NOT NULL,
    malt_id      INTEGER NOT NULL,
    amount_value DECIMAL NOT NULL,
    amount_unit  TEXT    NOT NULL,
    CONSTRAINT fk_beer FOREIGN KEY (beer_id) REFERENCES beer (id),
    CONSTRAINT fk_malt FOREIGN KEY (malt_id) REFERENCES malt (id),
    PRIMARY KEY (beer_id, malt_id)
);

CREATE TABLE beer_hop
(
    id           INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    beer_id      INTEGER NOT NULL,
    hop_id       INTEGER NOT NULL,
    add          TEXT,
    amount_value DECIMAL NOT NULL,
    amount_unit  TEXT    NOT NULL,
    attribute    TEXT,
    CONSTRAINT fk_beer FOREIGN KEY (beer_id) REFERENCES beer (id),
    CONSTRAINT fk_hop FOREIGN KEY (hop_id) REFERENCES hop (id)
);

CREATE TABLE food_pairing
(
    id      INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    beer_id INTEGER NOT NULL,
    name    TEXT    NOT NULL,
    CONSTRAINT fk_beer FOREIGN KEY (beer_id) REFERENCES beer (id)
);
